stages:
  - test-build
  - dev-build
  - stage-build

test-build:
  stage: test-build
  variables:
    NODE_ENV: "test"
  script:
    - DIST_PATH=$PROJECT_BASE_PATH/agent/builds
    - BUILD_FILENAME=build.zip
    - yarn install
    - yarn build
    - zip $BUILD_FILENAME main.prod.js package.json app/package.json
    - mkdir -p $DIST_PATH
    - cp -f {$BUILD_FILENAME,package.json} $DIST_PATH
  when: manual
  only:
    - merge_requests
  tags:
    - agent-test-env

dev-build:
  stage: dev-build
  variables:
    NODE_ENV: "dev"
  script:
    - DIST_PATH=$PROJECT_BASE_PATH/agent/builds
    - BUILD_FILENAME=build.zip
    - yarn install
    - yarn build
    - zip $BUILD_FILENAME main.prod.js package.json app/package.json
    - mkdir -p $DIST_PATH
    - cp -f {$BUILD_FILENAME,package.json} $DIST_PATH
  only:
    - dev
  tags:
    - agent-dev-env

stage-build:
  stage: stage-build
  variables:
    NODE_ENV: "stage"
  script:
    - DIST_PATH=$PROJECT_BASE_PATH/agent/builds
    - BUILD_FILENAME=build.zip
    - yarn install
    - yarn build
    - zip $BUILD_FILENAME main.prod.js package.json app/package.json
    - mkdir -p $DIST_PATH
    - cp -f {$BUILD_FILENAME,package.json} $DIST_PATH
  only:
    - stage
  tags:
    - agent-stage-env
